[workspace]
resolver = "2"
members = ["xds-api", "xtask"]
default-members = ["xds-api"]

[workspace.dependencies]
tonic = "0.11"
tonic-build = "0.11"
pbjson = "0.7"
pbjson-build = "0.7"
prost = "0.12"
prost-build = "0.12"
prost-types = "0.12"
