# Proto dependencies for building the Envoy XDS APIs.
#
# The version of the envoy-data-plane repo here determines the version of all of
# the other dependencies in this file. The git refs here MUST match the versions
# listed in enovyproxy/data-plane-api.git/bazel/repository_locations.bzl.
[dependencies]
envoy-data-plane = { repo_url = "https://github.com/envoyproxy/data-plane-api.git", git_ref = "09409f495015a2a144d421300458d3ad49e20031" }
cncf-xds = { repo_url = "https://github.com/cncf/xds", git_ref = "2ac532fd44436293585084f8d94c6bdb17835af0" }
protoc-gen-validate = { repo_url = "https://github.com/bufbuild/protoc-gen-validate", git_ref = "v1.0.4" }
googleapis = { repo_url = "https://github.com/googleapis/googleapis", git_ref = "fd52b5754b2b268bc3a22a10f29844f206abb327" }
opentelemetry-proto = { repo_url = "https://github.com/open-telemetry/opentelemetry-proto", git_ref = "v1.7.0", proto_root = "src" }
prometheus-client-model = { repo_url = "https://github.com/prometheus/client_model", git_ref = "v0.6.2" }
