name: Regression Build and Test

on: 
  push:
    branches: [ "main", "fix-protoc" ]
    
  pull_request:
    branches: [ "main", "fix-protoc" ]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "27.3"

    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
